name: Test coverage check

on:
  push:
    branches: [ '*' ]


jobs:

  pytest_cases:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        python -m poetry install

    - name: Run pytest coverage report
      run:
        pytest --cov=src/fab_ad --cov-fail-under=90 tests/ | grep TOTAL | awk -v N=4 '{print $4}'
