name: Pytest test cases

on:
  push:
    branches: [ 'milestone2*' ]


jobs:

  pytest_cases:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        python -m poetry install

    - name: Test with python unittest
      run:
        python -m pytest tests/